### ISSUE TITLE
Syntax for Autoimplicits

### ISSUE THREAD

**Issue by zampino** [fredokun/LaTTe#29]
Would it be possible to also support autoimplicits like in the following example?

```clojure
(definition lower-bound
   "`l` is a lower bound for set `S` in the ordering relation `R`."
   [[?T :type] [R (rel T T)] [S (set T)] [l T]]
   (forall-in [e S] (R l e)))
```
Meaning that when you use the definition `lower-bound` the argument T can be skipped and the term would be applied to 3 parameters only `(lower-bound R S I)`. 

I cannot see immediately how this would reflect on the defimplicit expansion. 

Another variant would be to put the ? even outside of the binding: like ?[T :type].

Maybe I’m influenced by Agda which expresses implicit arguments like so: 

```
id : {A : Set} -> A -> A
id x = x
```

the argument between braces doesn't need to be explicitly mentioned in the term implementation but can be referenced in the rest of the typing signature.

**Comment by fredokun** [comment]
Thanks for the suggestion... Indeed, that's a little more more verbose but more explicit and easy-to-grasp syntax for implicit type parameters. This is supported starting from https://github.com/latte-central/LaTTe/commit/2381bf93c2ae36619af2809ff7693ffd2ba6dee3 (release beta 5 https://github.com/latte-central/LaTTe/releases/tag/v1.0b5-SNAPSHOT)
